dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- name: damo
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: dumo
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: chindawn
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
